"""Add InfrastructureNode and VideoAsset

Revision ID: 0727bace4312
Revises: 473c4356f21a
Create Date: 2026-10-01 21:57:17.895169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '0727bace4312'
down_revision: Union[str, Sequence[str], None] = '473c4356f21a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('asset_type', sa.String(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('stream_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('infrastructure_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=True),
    sa.Column('node_type', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('alerts', sa.Column('video_asset_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_alerts_video_asset_id', 'alerts', 'video_assets', ['video_asset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.drop_column('alerts', 'video_asset_id')
    op.drop_index('idx_infrastructure_nodes_geometry', table_name='infrastructure_nodes', postgresql_using='gist')
    op.drop_table('infrastructure_nodes')
    op.drop_index('idx_video_assets_location', table_name='video_assets', postgresql_using='gist')
    op.drop_table('video_assets')
    # ### end Alembic commands ###
